version: '3.8'

services:
  frontend:
    image: my-react-app  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: my-python-api-app  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql_db
    image: my-mysql-db  # ✅ Ensure `image` is a string
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: nandhu01
      MYSQL_DATABASE: user_db
    ports:
      - "3308:3306"
