version: '3.8'

services:
  frontend:
    image: my-react-app
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: my-python-api-app
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: my-mysql-db
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: nandhu01
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

